src/LocadoraVeiculos.WebApplication/Controllers/CupomController.cs
using AutoMapper;
using LocadoraVeiculos.Aplicacao.CupomModule;
using LocadoraVeiculos.Dominio.CupomModule;
using LocadoraVeiculos.WebApplication.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LocadoraVeiculos.WebApplication.Controllers
{
    public class CupomController : Controller
    {
        private readonly ICupomRepository cupomRepository;
        private readonly IParceiroRepository parceiroReporitoy;
        private readonly ICupomAppService cupomAppService;
        private readonly IMapper mapper;

        public CupomController(ICupomRepository cupomRepository,
            IParceiroRepository parceiroReporitoy,
            ICupomAppService cupomAppService,
            IMapper mapper)
        {
            this.cupomRepository = cupomRepository;
            this.parceiroReporitoy = parceiroReporitoy;
            this.cupomAppService = cupomAppService;
            this.mapper = mapper;
        }

        // GET: CupomController
        public ActionResult Index()
        {
            var cupons = cupomRepository.SelecionarTodos();

            var cupomIndexVM = mapper.Map<CupomIndexViewModel>(cupons);

            return View(cupomIndexVM);
        }       

        // GET: CupomController/Create
        public ActionResult Create()
        {
            var parceiros = parceiroReporitoy.SelecionarTodos();

            var cupomCreateVM = new CupomCreateViewModel();

            cupomCreateVM.Parceiros = mapper.Map<List<SelectListItem>>(parceiros);

            return View(cupomCreateVM);
        }

        // POST: CupomController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CupomCreateViewModel cupomCreateVM)
        {
            try
            {
                var cupom = mapper.Map<Cupom>(cupomCreateVM);

                cupomAppService.RegistrarNovoCupom(cupom);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CupomController/Edit/5
        public ActionResult Edit(int id)
        {
            var cupom = cupomRepository.SelecionarPorId(id);

            var parceiros = parceiroReporitoy.SelecionarTodos();

            var cupomEditVM = mapper.Map<CupomEditViewModel>(cupom);

            cupomEditVM.Parceiros = mapper.Map<List<SelectListItem>>(parceiros);

            return View(cupomEditVM);
        }

        // POST: CupomController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CupomEditViewModel cupomEditVM)
        {
            try
            {
                var cupom = mapper.Map<Cupom>(cupomEditVM);

                cupomAppService.EditarCupom(id, cupom);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CupomController/Details/5
        public ActionResult Details(int id)
        {
            var cupom = cupomRepository.SelecionarPorId(id);
            
            var cupomDetailsVM = mapper.Map<CupomDetailsViewModel>(cupom);

            return View(cupomDetailsVM);
        }

        // GET: CupomController/Delete/5
        public ActionResult Delete(int id)
        {
            var cupom = cupomRepository.SelecionarPorId(id);

            var cupomDeleteVM = mapper.Map<CupomDeleteViewModel>(cupom);

            return View(cupomDeleteVM);
        }

        // POST: CupomController/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                cupomAppService.ExcluirCupom(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/LocadoraVeiculos.WebApplication/Controllers/ParceiroController.cs
using AutoMapper;
using LocadoraVeiculos.Aplicacao.CupomModule;
using LocadoraVeiculos.Dominio.CupomModule;
using LocadoraVeiculos.WebApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LocadoraVeiculos.WebApplication.Controllers
{
    public class ParceiroController : Controller
    {
        private readonly IParceiroAppService parceiroAppService;
        private readonly IParceiroRepository parceiroRepository;
        private readonly IMapper mapper;

        public ParceiroController(IParceiroAppService parceiroAppService,
            IParceiroRepository parceiroRepository,
            IMapper mapper)
        {
            this.parceiroAppService = parceiroAppService;
            this.parceiroRepository = parceiroRepository;
            this.mapper = mapper;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var parceiros = parceiroRepository.SelecionarTodos();

            var parceiroIndexVM =
                mapper.Map<ParceiroIndexViewModel>(parceiros);

            return View(parceiroIndexVM);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var parceiro = parceiroRepository.SelecionarPorId(id);

            var parceiroDetailsVM =
                mapper.Map<ParceiroDetailsViewModel>(parceiro);

            if (parceiroDetailsVM == null)
            {
                return NotFound();
            }

            return View(parceiroDetailsVM);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var parceiroCreateVM = new ParceiroCreateViewModel();

            return View(parceiroCreateVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ParceiroCreateViewModel parceiroCreateVM)
        {
            Parceiro parceiro = mapper.Map<Parceiro>(parceiroCreateVM);

            parceiroAppService.RegistrarNovoParceiro(parceiro);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var parceiro = parceiroRepository.SelecionarPorId(id);

            var parceiroEditVM =
                mapper.Map<ParceiroEditViewModel>(parceiro);

            if (parceiroEditVM == null)
            {
                return NotFound();
            }

            return View(parceiroEditVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ParceiroEditViewModel parceiroEditVM)
        {
            var parceiro = mapper.Map<Parceiro>(parceiroEditVM);

            parceiroAppService.EditarParceiro(id, parceiro);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var parceiro = parceiroRepository.SelecionarPorId(id);

            var parceiroDeleteVM =
                mapper.Map<ParceiroDeleteViewModel>(parceiro);

            if (parceiroDeleteVM == null)
            {
                return NotFound();
            }

            return View(parceiroDeleteVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var parceiro = parceiroRepository.SelecionarPorId(id);

            if (parceiro == null)
                return NotFound();

            parceiroAppService.ExcluirParceiro(id);

            return RedirectToAction("Index");
        }
    }
}

src/LocadoraVeiculos.WebApplication/Views/Shared/_Header.cshtml
@model LocadoraVeiculos.WebApplication.ViewModels.ITituloViewModel

@{
    ViewData["Title"] = Model.Titulo;
}

<div id="jumbo" class="jumbotron">
    <div class="container">
        <h1 class="display-3">@Model.Titulo</h1>
    </div>
</div>

src/LocadoraVeiculos.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Locadora Web - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!-- https://getbootstrap.com.br/docs/4.1/examples/jumbotron/?# -->

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Locadora de Veículos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link"  asp-action="Index" asp-controller="Home">Home <span class="sr-only">(atual)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cadastros</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" asp-action="Index" asp-controller="Parceiro">Parceiros</a>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Cupom">Cupons</a>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Locações</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Locação de Veículos</a>
                        <a class="dropdown-item" href="#">Devolução de Veículos</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Configurações <span class="sr-only">(atual)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <main role="main">        

        @await RenderSectionAsync("Header", required: false)

        <div class="container">
            @RenderBody()
        </div>

    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("ValidationScripts", required: false)
</body>
</html>